// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb9g-kYfHiCjb-hKUw1nOCdqgxiFklqkQ',
    appId: '1:420635386839:web:645f1cab6b89d7f97fe192',
    messagingSenderId: '420635386839',
    projectId: 'ahadi-af7dc',
    authDomain: 'ahadi-af7dc.firebaseapp.com',
    storageBucket: 'ahadi-af7dc.firebasestorage.app',
    measurementId: 'G-CDXMB4NRD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbHTuEJtFf669S04edYyPP0zfqAc6hI8o',
    appId: '1:420635386839:android:4030e03504e45fb27fe192',
    messagingSenderId: '420635386839',
    projectId: 'ahadi-af7dc',
    storageBucket: 'ahadi-af7dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZSnT9gQHMEKGaui1QWv4k1teAzc-USH8',
    appId: '1:420635386839:ios:3e4a449d5d74b27d7fe192',
    messagingSenderId: '420635386839',
    projectId: 'ahadi-af7dc',
    storageBucket: 'ahadi-af7dc.firebasestorage.app',
    iosBundleId: 'com.quantumvisiontech.ahadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZSnT9gQHMEKGaui1QWv4k1teAzc-USH8',
    appId: '1:420635386839:ios:d5e2f1ad710a50f17fe192',
    messagingSenderId: '420635386839',
    projectId: 'ahadi-af7dc',
    storageBucket: 'ahadi-af7dc.firebasestorage.app',
    iosBundleId: 'com.example.ahadi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb9g-kYfHiCjb-hKUw1nOCdqgxiFklqkQ',
    appId: '1:420635386839:web:8048facc59363dca7fe192',
    messagingSenderId: '420635386839',
    projectId: 'ahadi-af7dc',
    authDomain: 'ahadi-af7dc.firebaseapp.com',
    storageBucket: 'ahadi-af7dc.firebasestorage.app',
    measurementId: 'G-8Z57W8D46K',
  );
}
